# Generated by Django 3.2.20 on 2023-07-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=58)),
                ('phone2', models.CharField(blank=True, max_length=58, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('email2', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
