# Generated by Django 3.2.20 on 2023-07-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('heading', models.CharField(max_length=250)),
                ('message_body', models.TextField()),
                ('acknowledged', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_submitted', 'acknowledged'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-date_submitted'], name='contact_con_date_su_8107ee_idx'),
        ),
    ]
