# Generated by Django 3.2.20 on 2023-08-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productreview_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-name',)},
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
